# Directory and file filters

excluded:
  - Resources

# Enabled/disabled rules
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - all
disabled_rules:
  - anonymous_argument_in_multiline_closure
  - anyobject_protocol
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - convenience_type
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_types_order
  - function_default_parameter_at_end
  - indentation_width
  - inert_defer
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - one_declaration_per_file
  - prefer_nimble
  - prefixed_toplevel_constant
  - required_deinit
  - sorted_enum_cases
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - type_contents_order
  - unused_capture_list
  - vertical_whitespace_between_cases
  - trailing_whitespace
  - vertical_whitespace_opening_braces
  # @DependencyなどはTCAの公式にならって一行で記載したいのでルール削除
  - attributes
  - multiple_closures_with_trailing_closure
  # elseの{は改行して入れてたい
  - statement_position
  # if ブロックで return していても elseを記載した方が見やすいケースがあると思うのでルール削除
  - superfluous_else
  # 個人的にはreturnは省略したくない派
  - implicit_return
  # fileprivate を避ける理由がよくわからぬ！
  - private_over_fileprivate

# Configurations
attributes:
  always_on_line_above:
    - "@ConfigurationElement"
    - "@OptionGroup"
    - "@RuleConfigurationDescriptionBuilder"
balanced_xctest_lifecycle: &unit_test_configuration
  test_parent_classes:
    - SwiftLintTestCase
    - XCTestCase
closure_body_length:
  warning: 50
  error: 100
empty_xctest_method: *unit_test_configuration
file_name:
  excluded:
    - Exports.swift
    - GeneratedTests.swift
    - RuleConfigurationMacros.swift
    - SwiftSyntax+SwiftLint.swift
    - TestHelpers.swift
final_test_case: *unit_test_configuration
function_body_length: 60
identifier_name:
  excluded:
    - id
large_tuple: 3
number_separator:
  minimum_length: 5
prefer_key_path:
  restrict_to_standard_functions: false
redundant_type_annotation:
  consider_default_literal_types_redundant: true
single_test_class: *unit_test_configuration
type_body_length: 400
unneeded_override:
  affect_initializers: true
unused_import:
  always_keep_imports:
    - SwiftSyntaxBuilder # we can't detect uses of string interpolation of swift syntax nodes
    - SwiftLintFramework # now that this is a wrapper around other modules, don't treat as unused
line_length:
  ignores_comments: true
  ignores_urls: true
