# Directory and file filters
excluded:
  - Resources

opt_in_rules:
  - attributes

# Configurations
attributes:
  always_on_same_line:
    - "@Dependency"
nesting:
  type_level:
    warning: 2
cyclomatic_complexity:
  # Reducerのブロックはどうしてもswitchのcase数が増えてしまうので、switchのcaseに関しては複雑性をカウントしないようにする
  ignores_case_statements: true
