# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CheckBuild_Test_Swift

on:
  pull_request:
    branches:
      - "BR_develop**"
      - "BR_topic/**"
    paths-ignore:
      - "doc/*"
      - "wiki/**"
      - README.md
  issue_comment:
    types: [created, edited, deleted]

env:
  # チェックアウト
  DEVELOPER_DIR: /Applications/Xcode_16.3.app
  WORKSPACE_DIR: ./Macho/Macho.xcworkspace
  TARGET_SCHEME: Macho
  GOOGLE_SERVICE_INFO_PLIST_PATH: ./Macho/Macho/GoogleService-Info.plist
  SPM_PACKAGE_RESOLVED_FILE_PATH: Macho/Macho.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

jobs:
  build:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'test-this-please' || !github.event.issue.pull_request }}
    # 実行環境はmacosに設定
    runs-on: macos-15
    steps:
      # fetch-depth の計算
      - run: echo "fetch_depth=$(( commits + 1 ))" >> $GITHUB_ENV
        env:
          commits: ${{ github.event.pull_request.commits }}

      # チェックアウト(リポジトリからソースコードを取得)
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: ${{ env.fetch_depth }}

      # Xcodeの一覧出力
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'

      # Xcodeのバージョン選択
      - name: Select Xcode version
        run: sudo xcode-select -s '${{ env.DEVELOPER_DIR }}/Contents/Developer'

      # Xcodeのバージョン出力
      - name: Show Xcode version
        run: xcodebuild -version

      # DangerJSをインストール
      - name: Install Dnager JS
        run: npm install -g danger

      # SPMのライブラリのキャッシュ
      - name: Cache Swift Packages
        uses: actions/cache@v4.2.0
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles(env.SPM_PACKAGE_RESOLVED_FILE_PATH) }}
          restore-keys: ${{ runner.os }}-spm-

      # FirebaseのInfo.plistを復元
      - name: decode Info.plist for firebase
        run: |
          echo ${{ secrets.FIREBASE_INFO }} | base64 -o ${{ env.GOOGLE_SERVICE_INFO_PLIST_PATH }} -D

      # ビルド
      - name: Xcode Resolve Package Dependencies
        run: set -o pipefail &&
          xcodebuild
          -workspace ${WORKSPACE_DIR}
          -scheme $TARGET_SCHEME
          -configuration Debug
          -clonedSourcePackagesDirPath SourcePackages
          -skipPackagePluginValidation
          -skipMacroValidation
          -scmProvider xcode
          -resolvePackageDependencies

      # 単体テストの実行
      - name: Xcode test
        run: set -o pipefail &&
          xcodebuild
          -workspace ${WORKSPACE_DIR}
          -configuration Debug
          -destination 'platform=iOS Simulator,OS=18.1,name=iPhone 16 Pro'
          -scheme $TARGET_SCHEME
          -skipPackagePluginValidation
          -skipMacroValidation
          -scmProvider xcode
          -clonedSourcePackagesDirPath SourcePackages
          -resultBundlePath 'Build/test.xcresult'
          -enableCodeCoverage YES
          test

      # テスト結果の確認
      - name: Analyze Danger
        run: swift run danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_TOKEN }}
