# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: regression_test

on:
  pull_request:
    branches:
      - "BR_develop**"
      - "BR_topic/**"
  workflow_dispatch:

env:
  # チェックアウト
  DEVELOPER_DIR: /Applications/Xcode_16.1.app
  WORKSPACE_DIR: ./Macho/Macho.xcworkspace
  GOOGLE_SERVICE_INFO_PLIST_PATH: ./Macho/Macho/GoogleService-Info.plist
  SPM_PACKAGE_RESOLVED_FILE_PATH: Macho/Macho.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DERIVED_DATA_PATH: "./Build/DerivedData"
  APP_NAME: "Macho"
  BUILD_CONFIG: "Debug"
  SIM_NAME: "iPhone 16 Pro"
  SIM_OS_VERSION: "18.1"
  DESTINATION: "platform=iOS Simulator,OS=$SIM_OS_VERSION,name=$SIM_NAME"

jobs:
  build:
    # 実行環境はmacosに設定
    runs-on: macos-15

    steps:
      # fetch-depth の計算
      - run: echo "fetch_depth=$(( commits + 1 ))" >> $GITHUB_ENV
        env:
          commits: ${{ github.event.pull_request.commits }}

      # チェックアウト(リポジトリからソースコードを取得)
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: ${{ env.fetch_depth }}

      # E2Eテスト実行用のシミュレーターを事前に起動しておく
      - name: "Boot Simulator"
        run: scripts/boot_simulator.sh "$SIM_NAME" "iOS $SIM_OS_VERSION"

      # Xcodeの一覧出力
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'

      # Xcodeのバージョン選択
      - name: Select Xcode version
        run: sudo xcode-select -s '${{ env.DEVELOPER_DIR }}/Contents/Developer'

      # Xcodeのバージョン出力
      - name: Show Xcode version
        run: xcodebuild -version

      # Maestroインストール
      - name: Install Maestro
        run: bash scripts/create_e2e_env.sh

      # SPMのライブラリのキャッシュ
      - name: Cache Swift Packages
        uses: actions/cache@v4.2.0
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles(env.SPM_PACKAGE_RESOLVED_FILE_PATH) }}
          restore-keys: ${{ runner.os }}-spm-

      # FirebaseのInfo.plistを復元
      - name: decode Info.plist for firebase
        run: |
          echo ${{ secrets.FIREBASE_INFO }} | base64 -o ${{ env.GOOGLE_SERVICE_INFO_PLIST_PATH }} -D

      # SPMライブラリ依存解決
      - name: Xcode Resolve Package Dependencies
        run: set -o pipefail &&
          xcodebuild
          -workspace "$WORKSPACE_DIR"
          -scheme Macho
          -configuration "$BUILD_CONFIG"
          -clonedSourcePackagesDirPath SourcePackages
          -skipPackagePluginValidation
          -skipMacroValidation
          -scmProvider xcode
          -resolvePackageDependencies

      # ビルド
      - name: Xcode Resolve Package Dependencies
        run: |
          DESTINATION="platform=iOS Simulator,OS=$SIM_OS_VERSION,name=$SIM_NAME"
          set -o pipefail &&
          xcodebuild
          -workspace "${WORKSPACE_DIR}"
          -scheme Macho
          -configuration "$BUILD_CONFIG"
          -destination "$DESTINATION"
          -derivedDataPath "$DERIVED_DATA_PATH"
          -clonedSourcePackagesDirPath SourcePackages
          -skipPackagePluginValidation
          -skipMacroValidation
          -scmProvider xcode
          build | xcbeautify

      # アプリインストール
      - name: Install app
        run: |
          APP_PATH="$DERIVED_DATA_PATH/Build/Products/$BUILD_CONFIG-iphonesimulator/$APP_NAME.app"
          xcrun simctl install booted "$APP_PATH"

      # E2Eテスト実行
      - name: Do E2E Test
        working-directory: E2E
        run: maestro test main.yml
